language: python
sudo: true

python:
  - 2.7

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20170106/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget aria2 axel curl graphviz
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self --all
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1
  - tlmgr install xindy
  - tlmgr install mweights
  - tlmgr install babel-french
  - tlmgr remove --force download
  - pip install dot2tex
  - pip install graphviz

script:
  - make a4
  - make c5

after_success:
  - git config user.name "Arukana"
  - git config user.email "arukana@users.noreply.github.com"
  - cd dest
  - git init
  - git add neko-a4.pdf
  - git add neko-c5.pdf
  - git commit -m "Initial gh-pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/Arukana/book.git" master:gh-pages
