---
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends texlive-base texlive-xetex latex-xcolor xzdec
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended
  - sudo apt-get install -y --no-install-recommends graphviz
  - mkdir -p $HOME/texmf
  - tlmgr init-usertree
  - sudo tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final 
  - sudo tlmgr update --self --all
  - sudo tlmgr install ctex l3kernel xecjk l3packages latex
  - sudo tlmgr install geometry fontspec fandol ulem zhnumber
  - sudo tlmgr install babel-french
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install dot2tex
script:
  - make a4
  - make c5
addons:
  apt:
      packages:
            - texlive-latex-recommended
                  - texlive-latex-extra
                  - texlive-fonts-recommended