---
language: python
sudo: false
os:
  - osx
python:
  - 2.7
before_install:
  - brew install graphviz
  - mkdir -p texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC texlive
install:
  - pip install dot2tex
  - pip install graphviz
  - tlmgr update --self --all
  - tlmgr install babel-french
script:
  - make a4
  - make c5
addons:
  apt:
      packages:
            - texlive-latex-recommended
                  - texlive-latex-extra
                  - texlive-fonts-recommended